# Generated by Django 5.1.6 on 2025-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='escolas/fundos/'),
        ),
    ]
