# Generated by Django 5.1.6 on 2025-04-14 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0020_escola_imagem_fundo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Ficha de Matrícula'), ('declaracao', 'Declaração de Matrícula')], max_length=20)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('html_gerado', models.TextField()),
                ('assinada_diretor', models.BooleanField(default=False)),
                ('data_assinatura_diretor', models.DateTimeField(blank=True, null=True)),
                ('assinada_secretario', models.BooleanField(default=False)),
                ('data_assinatura_secretario', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='alunos.aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
    ]
