# Generated by Django 5.1.6 on 2025-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_documentoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
