# Generated by Django 5.1.6 on 2025-04-19 18:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0022_funcionario_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='imagem_fundo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de fundo'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
