# Generated by Django 5.1.6 on 2025-04-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Pedagógico', 'Pedagógico')], default='Administrativo', max_length=20),
        ),
    ]
