# Generated by Django 5.1.6 on 2025-04-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='planejamento',
            new_name='tem_planejamento',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario_planejamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controle.setor'),
            preserve_default=False,
        ),
    ]
