# Generated by Django 5.1.6 on 2025-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_rename_planejamento_funcionario_tem_planejamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='sabado_letivo',
            field=models.BooleanField(default=False),
        ),
    ]
