# Generated by Django 5.1.6 on 2025-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_funcionario_sabado_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='sabado_letivo',
            field=models.BooleanField(default=False),
        ),
    ]
