# Generated by Django 5.1.6 on 2025-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_feriado_sabado_letivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabadoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
