# Generated by Django 5.1.6 on 2025-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
