# Generated by Django 5.1.6 on 2025-04-19 18:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de fundo'),
        ),
    ]
