# Generated by Django 5.1.6 on 2025-05-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_alter_escola_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabalho',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariotrabalho',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
