# Generated by Django 5.1.6 on 2025-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_funcionario_bairro_funcionario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='serie',
            field=models.CharField(blank=True, choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('4º ANO', '4º ANO'), ('5º ANO', '5º ANO'), ('6º ANO', '6º ANO'), ('7º ANO', '7º ANO'), ('8º ANO', '8º ANO'), ('9º ANO', '9º ANO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='turma',
            field=models.CharField(blank=True, choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E'), ('F', 'Turma F'), ('G', 'Turma G')], max_length=1, null=True),
        ),
    ]
