# Generated by Django 5.1.6 on 2025-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_funcionario_serie_alter_funcionario_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='turma',
            field=models.CharField(blank=True, choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E'), ('F', 'Turma F'), ('G', 'Turma G')], max_length=10, null=True),
        ),
    ]
