# Generated by Django 5.1.6 on 2025-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_alter_funcionario_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='fim_ferias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fonte_pagadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inicio_ferias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('Efetivo', 'Efetivo'), ('Contratado', 'Contratado')], max_length=20, null=True),
        ),
    ]
