# Generated by Django 5.1.6 on 2025-08-21 15:46

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_funcionario_fim_ferias_funcionario_fonte_pagadora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da prefeitura')),
            ],
            options={
                'verbose_name': 'Prefeitura',
                'verbose_name_plural': 'Prefeituras',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vínculo opcional com usuário do sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da secretaria')),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretarias', to='controle.prefeitura')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'unique_together': {('prefeitura', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='controle.secretaria'),
        ),
        migrations.AddField(
            model_name='setor',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='controle.secretaria'),
        ),
        migrations.CreateModel(
            name='AcessoSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_secretaria', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='controle.secretaria')),
            ],
            options={
                'verbose_name': 'Acesso à Secretaria',
                'verbose_name_plural': 'Acessos às Secretarias',
                'unique_together': {('user', 'secretaria')},
            },
        ),
    ]
